somma: array.o utils.o driver_somma.o
	gcc array.o utils.o driver_somma.o -o driver_somma.exe

array.o:
	gcc -c array.c

utils.o:
	gcc -c utils.c

driver_somma.o:
	gcc -c driver_somma.c

clean:
	rm -f *.o *.exe