somma: array.o utils.o driver_sommaiesima.o
	gcc array.o utils.o driver_sommaiesima.o -o driver.exe

array.o:
	gcc -c array.c

utils.o:
	gcc -c utils.c

driver_sommaiesima.o:
	gcc -c driver_sommaiesima.c

clean:
	rm -f *.o *.exe